Repository nvbach91/4IZ278-2023-2024-LS, pull requests merged in 2024-03, with the labels that each got.

#50 hlas03-cv02
  www/hlas03/cv02/cv02/classes/Person.php
  www/hlas03/cv02/cv02/components/persons.php
  www/hlas03/cv02/cv02/css/main.css
  www/hlas03/cv02/cv02/includes/foot.php
  www/hlas03/cv02/cv02/includes/head.php
  www/hlas03/cv02/cv02/index.php
Labels: needs fixing

#47 lean04-cv02
  www/lean04/cv02/classes/Address.php
  www/lean04/cv02/classes/Company.php
  www/lean04/cv02/classes/Person.php
  www/lean04/cv02/classes/Worker.php
  www/lean04/cv02/components/businessCard.php
  www/lean04/cv02/components/businessCards.php
  www/lean04/cv02/css/main.css
  www/lean04/cv02/includes/foot.php
  www/lean04/cv02/includes/head.php
  www/lean04/cv02/index.php
Labels: needs fixing

#42 boxd00-cv02
  www/boxd00/cv02/classes/Person.php
  www/boxd00/cv02/components/page.php
  www/boxd00/cv02/includes/footer.php
  www/boxd00/cv02/includes/header.php
  www/boxd00/cv02/index.php
  www/boxd00/cv02/static/style.css
  www/boxd00/cv02/utils/utils.php
Labels: needs fixing

#36 pycd01-cv02
  www/pycd01/cv02/classes/Person.php
  www/pycd01/cv02/img/aurelion.png
  www/pycd01/cv02/img/kayn.png
  www/pycd01/cv02/img/zed.png
  www/pycd01/cv02/index.php
  www/pycd01/cv02/src/foot.php
  www/pycd01/cv02/src/head.php
  www/pycd01/cv02/src/main.php
  www/pycd01/cv02/styles/style.css
  www/pycd01/cv02/utils/person_func.php
Labels: needs fixing

#34 lacp06-cv02
  www/lacp06/cv02/classes/Person.php
  www/lacp06/cv02/components/Cards.php
  www/lacp06/cv02/css.css
  www/lacp06/cv02/img/briefcase.svg
  www/lacp06/cv02/img/building.svg
  www/lacp06/cv02/img/home.svg
  www/lacp06/cv02/img/mail.svg
  www/lacp06/cv02/img/map.svg
  www/lacp06/cv02/img/phone.svg
  www/lacp06/cv02/img/portfolio.svg
  www/lacp06/cv02/img/user.svg
  www/lacp06/cv02/includes/footer.php
  www/lacp06/cv02/includes/head.php
  www/lacp06/cv02/index.php
  www/lacp06/cv02/utils/functions.php
Labels: needs fixing

#52 auza00-cv03
  www/auza00/cv03/index.php
Labels: approved

#53 lacp06-cv03
  www/lacp06/cv03/css.css
  www/lacp06/cv03/includes/footer.php
  www/lacp06/cv03/includes/header.php
  www/lacp06/cv03/index.php
Labels: approved

#58 chav07-cv03
  www/chav07/cv03/components/registrationForm.php
  www/chav07/cv03/includes/bottom.php
  www/chav07/cv03/includes/top.php
  www/chav07/cv03/index.php
  www/chav07/cv03/main.css
Labels: approved

#62 mald16-cv03
  www/mald16/cv03/components/form.php
  www/mald16/cv03/includes/foot.php
  www/mald16/cv03/includes/head.php
  www/mald16/cv03/index.php
  www/mald16/cv03/utils/logic.php
Labels: approved

#63 brud06-cv03
  www/brud06/cv03/css/style.css
  www/brud06/cv03/includes/foot.php
  www/brud06/cv03/includes/head.php
  www/brud06/cv03/index.php
Labels: approved

#64 nikd01-cv03
  www/nikd01/cv03/css/style.css
  www/nikd01/cv03/includes/foot.php
  www/nikd01/cv03/includes/head.php
  www/nikd01/cv03/index.php
Labels: approved

#65 talp03-cv03
  www/talp03/cv03/css/style.css
  www/talp03/cv03/index.php
Labels: approved

#66 jana19-cv03
  www/jana19/cv03/includes/foot.php
  www/jana19/cv03/includes/head.php
  www/jana19/cv03/index.php
Labels: approved

#68 poij00-cv03
  www/poij00/cv03/body.php
  www/poij00/cv03/footer.php
  www/poij00/cv03/header.php
  www/poij00/cv03/index.php
  www/poij00/cv03/style.css
  www/poij00/cv03/variables.php
Labels: approved

#69 kouv13-cv03
  www/kouv13/cv03/components/app.php
  www/kouv13/cv03/components/body.php
  www/kouv13/cv03/components/head.php
  www/kouv13/cv03/index.php
Labels: approved

#70 adad05-cv03
  www/adad05/cv03/components/main.php
  www/adad05/cv03/css/main.css
  www/adad05/cv03/includes/footer.php
  www/adad05/cv03/includes/head.php
  www/adad05/cv03/index.php
Labels: approved

#71 hlas03-cv03
  www/hlas03/cv03/cv03/components/form.php
  www/hlas03/cv03/cv03/css/main.css
  www/hlas03/cv03/cv03/forms/form.php
  www/hlas03/cv03/cv03/includes/foot.php
  www/hlas03/cv03/cv03/includes/head.php
  www/hlas03/cv03/cv03/index.php
Labels: approved

#74 kref01-cv03
  www/kref01/cv03/components/form.php
  www/kref01/cv03/css/style.css
  www/kref01/cv03/includes/foot.php
  www/kref01/cv03/includes/head.php
  www/kref01/cv03/index.php
Labels: approved

#29 lors01-cv02
  www/lors01/cv02/classes/Person.php
  www/lors01/cv02/components/footer.php
  www/lors01/cv02/components/header.php
  www/lors01/cv02/components/utils.php
  www/lors01/cv02/images/airbnb-cleaning-min.png
  www/lors01/cv02/images/checkmark2.png
  www/lors01/cv02/images/ic_launcher.png
  www/lors01/cv02/index.php
  www/lors01/cv02/styles/style.css
Labels: invalid PR, needs fixing

#35 srnj01-cv02
  www/srnj01/cv02/assets/anakin-avatar.png
  www/srnj01/cv02/assets/anakin.png
  www/srnj01/cv02/assets/obiwan-avatar.png
  www/srnj01/cv02/assets/obiwan.png
  www/srnj01/cv02/assets/yoda-avatar.png
  www/srnj01/cv02/assets/yoda.png
  www/srnj01/cv02/classes/Person.php
  www/srnj01/cv02/components/BusinessCards.php
  www/srnj01/cv02/includes/assets/globe.php
  www/srnj01/cv02/includes/assets/mail.php
  www/srnj01/cv02/includes/assets/map.php
  www/srnj01/cv02/includes/assets/phone.php
  www/srnj01/cv02/includes/footer.php
  www/srnj01/cv02/includes/header.php
  www/srnj01/cv02/index.php
  www/srnj01/cv02/utils/personalInfo.php
Labels: needs fixing

#56 pycd01-cv03
  www/pycd01/cv03/index.php
  www/pycd01/cv03/styles/style.css
Labels: needs fixing

#59 lukt03-cv03
  www/lukt03/cv03/css/style.css
  www/lukt03/cv03/includes/foot.php
  www/lukt03/cv03/includes/head.php
  www/lukt03/cv03/index.php
Labels: needs fixing

#60 fanm02-cv03
  www/fanm02/cv03/components/footer.php
  www/fanm02/cv03/components/header.php
  www/fanm02/cv03/index.php
  www/fanm02/cv03/styles/style.css
Labels: needs fixing

#61 boxd00-cv03
  www/boxd00/cv03/includes/footer.php
  www/boxd00/cv03/includes/header.php
  www/boxd00/cv03/index.php
  www/boxd00/cv03/static/style.css
Labels: needs fixing

#73 srnj01-cv03
  www/srnj01/cv03/index.php
Labels: needs fixing

#83 sebv03-cv02
  www/sebv03/cv01/index.php
  www/sebv03/cv02/classes/Person.php
  www/sebv03/cv02/components/people.php
  www/sebv03/cv02/css/main.css
  www/sebv03/cv02/includes/foot.php
  www/sebv03/cv02/includes/head.php
  www/sebv03/cv02/includes/listPeople.php
  www/sebv03/cv02/index.php
Labels: approved, late PR

#85 iblt00-cv03
  www/iblt00/cv03/components/form.php
  www/iblt00/cv03/includes/footer.php
  www/iblt00/cv03/includes/header.php
  www/iblt00/cv03/index.php
  www/iblt00/cv03/styles/main.css
Labels: approved, late PR

#67 lors01-cv03
  www/lors01/cv03/components/footer.php
  www/lors01/cv03/components/header.php
  www/lors01/cv03/index.php
Labels: needs fixing

#76 davj05-cv03
  www/davj05/cv03/index.php
  www/davj05/cv03/static/styles.css
  www/davj05/cv03/views/foot.php
  www/davj05/cv03/views/head.php
Labels: needs fixing

#96 kref01-cv04
  www/kref01/cv04/admin/users.php
  www/kref01/cv04/components/registration.php
  www/kref01/cv04/css/style.css
  www/kref01/cv04/includes/foot.php
  www/kref01/cv04/includes/head.php
  www/kref01/cv04/index.php
  www/kref01/cv04/login.php
  www/kref01/cv04/test.txt
  www/kref01/cv04/users.db
  www/kref01/cv04/utils.php
Labels: invalid PR, needs fixing

#88 nikd01-cv04
  www/nikd01/cv04/admin/users.php
  www/nikd01/cv04/css/style.css
  www/nikd01/cv04/database/users.db
  www/nikd01/cv04/includes/foot.php
  www/nikd01/cv04/includes/head.php
  www/nikd01/cv04/index.php
  www/nikd01/cv04/login.php
  www/nikd01/cv04/utils/utils.php
Labels: needs fixing

#101 lors01-cv04
  www/lors01/cv04/admin/users.php
  www/lors01/cv04/components/footer.php
  www/lors01/cv04/components/header.php
  www/lors01/cv04/functions.php
  www/lors01/cv04/index.php
  www/lors01/cv04/login.php
  www/lors01/cv04/registration.php
  www/lors01/cv04/users.db
Labels: approved, late PR

#107 kouv13-cv05
  www/kouv13/cv05/db.php
  www/kouv13/cv05/index.php
Labels: approved

#109 adad05-cv05
  www/adad05/cv05/classes/Database.php
  www/adad05/cv05/classes/DatabaseConnection.php
  www/adad05/cv05/classes/DatabaseOperations.php
  www/adad05/cv05/classes/MatchesDB.php
  www/adad05/cv05/classes/PlayersDB.php
  www/adad05/cv05/classes/TeamsDB.php
  www/adad05/cv05/index.php
Labels: approved

#110 lukt03-cv05
  www/lukt03/cv05/.gitignore
  www/lukt03/cv05/database-config.example.php
  www/lukt03/cv05/database.php
  www/lukt03/cv05/index.php
Labels: approved

#111 lean04-cv05
  www/lean04/cv05/database.php
  www/lean04/cv05/index.php
Labels: approved
