Repository nvbach91/4IZ278-2023-2024-LS, pull requests merged in 2024-04, with the labels that each got.

#112 kref01-cv05
  www/kref01/cv05/classes/Database.php
  www/kref01/cv05/classes/DatabaseConnection.php
  www/kref01/cv05/classes/DatabaseOperations.php
  www/kref01/cv05/classes/MatchesDB.php
  www/kref01/cv05/classes/PlayersDB.php
  www/kref01/cv05/classes/TeamsDB.php
  www/kref01/cv05/components/tests.php
  www/kref01/cv05/css/style.css
  www/kref01/cv05/includes/foot.php
  www/kref01/cv05/includes/head.php
  www/kref01/cv05/index.php
Labels: needs fixing

#102 lacp06-cv05
  www/lacp06/cv05/database.php
  www/lacp06/cv05/db.php
  www/lacp06/cv05/includes/footer.php
  www/lacp06/cv05/includes/header.php
  www/lacp06/cv05/index.php
Labels: needs fixing

#103 pycd01-cv05
  www/pycd01/cv05/classes/Matches.php
  www/pycd01/cv05/classes/Players.php
  www/pycd01/cv05/classes/Teams.php
  www/pycd01/cv05/classes/Users.php
  www/pycd01/cv05/index.php
  www/pycd01/cv05/utils/db.php
Labels: needs fixing

#106 fanm02-cv05
  www/fanm02/cv05/components/db_test.php
  www/fanm02/cv05/components/footer.php
  www/fanm02/cv05/components/header.php
  www/fanm02/cv05/db/matches.php
  www/fanm02/cv05/db/players.php
  www/fanm02/cv05/db/teams.php
  www/fanm02/cv05/index.php
  www/fanm02/cv05/styles/style.css
  www/fanm02/cv05/utils/db.php
Labels: needs fixing

#99 davj05-cv04
  www/davj05/cv04/admin/users.php
  www/davj05/cv04/functions.php
  www/davj05/cv04/index.php
  www/davj05/cv04/login.php
  www/davj05/cv04/registration.php
  www/davj05/cv04/static/styles.css
  www/davj05/cv04/users.db
  www/davj05/cv04/views/foot.php
  www/davj05/cv04/views/head.php
Labels: needs fixing

#104 mald16-cv05
  www/mald16/cv05/database.php
  www/mald16/cv05/includes/foot.php
  www/mald16/cv05/includes/head.php
  www/mald16/cv05/index.php
  www/mald16/cv05/method-tests.php
Labels: needs fixing

#114 srnj01-cv05
  www/srnj01/cv05/database.php
  www/srnj01/cv05/includes/footer.php
  www/srnj01/cv05/includes/header.php
  www/srnj01/cv05/index.php
Labels: needs fixing

#122 lukt03-cv06
  www/lukt03/cv06/components/CategoryDisplay.php
  www/lukt03/cv06/components/ProductDisplay.php
  www/lukt03/cv06/components/SlideDisplay.php
  www/lukt03/cv06/config/.gitignore
  www/lukt03/cv06/config/config.example.php
  www/lukt03/cv06/css/mystyles.css
  www/lukt03/cv06/css/styles.css
  www/lukt03/cv06/db/CategoriesDB.php
  www/lukt03/cv06/db/Database.php
  www/lukt03/cv06/db/DatabaseConnection.php
  www/lukt03/cv06/db/DatabaseOperations.php
  www/lukt03/cv06/db/ProductsDB.php
  www/lukt03/cv06/db/SlidesDB.php
  www/lukt03/cv06/includes/foot.php
  www/lukt03/cv06/includes/head.php
  www/lukt03/cv06/index.php
Labels: approved

#119 fanm02-cv06
  www/fanm02/cv06/components/CategoryDisplay.php
  www/fanm02/cv06/components/ProductDisplay.php
  www/fanm02/cv06/components/SlideDisplay.php
  www/fanm02/cv06/db/CategoryDB.php
  www/fanm02/cv06/db/ProductDB.php
  www/fanm02/cv06/db/SlideDB.php
  www/fanm02/cv06/index.php
  www/fanm02/cv06/style/styles.css
  www/fanm02/cv06/utils/db.php
Labels: approved

#117 lacp06-cv06
  www/lacp06/cv06/db/database_eshop.php
  www/lacp06/cv06/db/db_eshop.php
  www/lacp06/cv06/includes/CategoryDisplay.php
  www/lacp06/cv06/includes/ProductDisplay.php
  www/lacp06/cv06/includes/SlideDisplay.php
  www/lacp06/cv06/index.php
  www/lacp06/cv06/styles.css
Labels: approved

#115 pycd01-cv06
  www/pycd01/cv06/classes/Categories.php
  www/pycd01/cv06/classes/Products.php
  www/pycd01/cv06/classes/Users.php
  www/pycd01/cv06/index.php
  www/pycd01/cv06/style.css
  www/pycd01/cv06/utils/db.php
Labels: approved

#123 mald16-cv06
  www/mald16/cv06/assets/favicon.ico
  www/mald16/cv06/components/carouselDisplay.php
  www/mald16/cv06/components/categoryDisplay.php
  www/mald16/cv06/components/productDisplay.php
  www/mald16/cv06/css/styles.css
  www/mald16/cv06/database/CarouselDB.php
  www/mald16/cv06/database/CategoriesDB.php
  www/mald16/cv06/database/ProductsDB.php
  www/mald16/cv06/database/db.php
  www/mald16/cv06/includes/foot.php
  www/mald16/cv06/includes/head.php
  www/mald16/cv06/index.php
Labels: needs fixing

#120 lean04-cv06
  www/lean04/cv06/components/CategoryDisplay.php
  www/lean04/cv06/components/ProductDisplay.php
  www/lean04/cv06/components/SlideDisplay.php
  www/lean04/cv06/css/styles.css
  www/lean04/cv06/database/CategoriesDB.php
  www/lean04/cv06/database/Database.php
  www/lean04/cv06/database/ProductsDB.php
  www/lean04/cv06/database/SlidesDB.php
  www/lean04/cv06/index.php
Labels: needs fixing

#116 lors01-cv05
  www/lors01/cv05/dbconn.php
  www/lors01/cv05/index.php
Labels: invalid PR, needs fixing

#121 brud06-cv06
  www/brud06/cv06/components/CategoryDisplay.php
  www/brud06/cv06/components/ProductDisplay.php
  www/brud06/cv06/components/SlideDisplay.php
  www/brud06/cv06/css/style.css
  www/brud06/cv06/db/CategoriesDB.php
  www/brud06/cv06/db/ProductsDB.php
  www/brud06/cv06/db/SlidesDB.php
  www/brud06/cv06/db/database.php
  www/brud06/cv06/images/WorksInLocalhost.PNG
  www/brud06/cv06/images/myphpadmin.PNG
  www/brud06/cv06/includes/body.php
  www/brud06/cv06/includes/head.php
  www/brud06/cv06/index.php
Labels: approved

#118 adad05-cv06
  www/adad05/cv06/classes/CategoriesDB.php
  www/adad05/cv06/classes/Database.php
  www/adad05/cv06/classes/DatabaseConnection.php
  www/adad05/cv06/classes/DatabaseOperations.php
  www/adad05/cv06/classes/ProductsDB.php
  www/adad05/cv06/classes/SlidesDB.php
  www/adad05/cv06/components/CategoryDisplay.php
  www/adad05/cv06/components/ProductDisplay.php
  www/adad05/cv06/components/SlideDisplay.php
  www/adad05/cv06/components/body.php
  www/adad05/cv06/css/styles.css
  www/adad05/cv06/includes/head.php
  www/adad05/cv06/index.php
Labels: needs fixing

#128 hlas03-cv05
  www/hlas03/cv05/database-constants.php
  www/hlas03/cv05/database.php
  www/hlas03/cv05/index.php
Labels: late PR, pass

#125 jana19-cv06
  www/jana19/cv06/components/CategoryDisplay.php
  www/jana19/cv06/components/ProductDisplay.php
  www/jana19/cv06/components/SlideDisplay.php
  www/jana19/cv06/config/constant.php
  www/jana19/cv06/css/styles.css
  www/jana19/cv06/db/CategoriesDB.php
  www/jana19/cv06/db/Database.php
  www/jana19/cv06/db/DatabaseConnection.php
  www/jana19/cv06/db/DatabaseOperations.php
  www/jana19/cv06/db/ProductsDB.php
  www/jana19/cv06/db/SlidesDB.php
  www/jana19/cv06/includes/footer.php
  www/jana19/cv06/includes/header.php
  www/jana19/cv06/index.html
  www/jana19/cv06/index.php
Labels: approved

#131 talp03-cv06
  www/talp03/cv06/classes/CategoryDB.php
  www/talp03/cv06/classes/ProductsDB.php
  www/talp03/cv06/css/styles.css
  www/talp03/cv06/includes/category.php
  www/talp03/cv06/includes/footer.php
  www/talp03/cv06/includes/head.php
  www/talp03/cv06/includes/navigation.php
  www/talp03/cv06/includes/products.php
  www/talp03/cv06/index.php
  www/talp03/cv06/utils/database.php
Labels: approved

#126 srnj01-cv06
  www/srnj01/cv06/components/carousel.php
  www/srnj01/cv06/components/nav.php
  www/srnj01/cv06/components/products.php
  www/srnj01/cv06/components/sidebar.php
  www/srnj01/cv06/db/db.php
  www/srnj01/cv06/db/eshop.php
  www/srnj01/cv06/includes/footer.php
  www/srnj01/cv06/includes/header.php
  www/srnj01/cv06/index.php
  www/srnj01/cv06/styles/main.css
Labels: approved

#130 pycd01-cv08
  www/pycd01/cv08/assets/avatar.svg
  www/pycd01/cv08/buy.php
  www/pycd01/cv08/cart.php
  www/pycd01/cv08/classes/Products.php
  www/pycd01/cv08/create-item.php
  www/pycd01/cv08/delete-item.php
  www/pycd01/cv08/edit-item.php
  www/pycd01/cv08/incl/footer.php
  www/pycd01/cv08/incl/header.php
  www/pycd01/cv08/incl/navbar.php
  www/pycd01/cv08/index.php
  www/pycd01/cv08/login.php
  www/pycd01/cv08/logout.php
  www/pycd01/cv08/profile.php
  www/pycd01/cv08/remove-item.php
  www/pycd01/cv08/style.css
  www/pycd01/cv08/utils/db.php
Labels: approved

#129 mald16-cv08
  www/mald16/cv08/buy.php
  www/mald16/cv08/cart.php
  www/mald16/cv08/create-item.php
  www/mald16/cv08/css/custom-styles.css
  www/mald16/cv08/css/styles.css
  www/mald16/cv08/db/db.php
  www/mald16/cv08/delete-item.php
  www/mald16/cv08/edit-item.php
  www/mald16/cv08/inc/foot.php
  www/mald16/cv08/inc/head.php
  www/mald16/cv08/index.php
  www/mald16/cv08/login.php
  www/mald16/cv08/logout.php
  www/mald16/cv08/remove-item.php
Labels: approved

#133 brud06-cv08
  www/brud06/cv08/buy.php
  www/brud06/cv08/cart.php
  www/brud06/cv08/components/GoodsDisplay.php
  www/brud06/cv08/create-item.php
  www/brud06/cv08/css/myStyle.css
  www/brud06/cv08/db/GoodsDB.php
  www/brud06/cv08/db/database.php
  www/brud06/cv08/delete-item.php
  www/brud06/cv08/edit-item.php
  www/brud06/cv08/includes/footer.php
  www/brud06/cv08/includes/header.php
  www/brud06/cv08/index.php
  www/brud06/cv08/login.php
  www/brud06/cv08/logout.php
  www/brud06/cv08/remove-item.php
Labels: approved

#138 lacp06-cv08
  www/lacp06/cv08/buy.php
  www/lacp06/cv08/cart.php
  www/lacp06/cv08/create-item.php
  www/lacp06/cv08/db/database_eshop.php
  www/lacp06/cv08/db/db_eshop.php
  www/lacp06/cv08/delete-item.php
  www/lacp06/cv08/edit-item.php
  www/lacp06/cv08/includes/Footer.php
  www/lacp06/cv08/includes/Header.php
  www/lacp06/cv08/includes/ProductDisplay.php
  www/lacp06/cv08/index.php
  www/lacp06/cv08/login.php
  www/lacp06/cv08/logout.php
  www/lacp06/cv08/remove-item.php
  www/lacp06/cv08/styles.css
Labels: approved

#142 srnj01-cv08
  www/srnj01/cv08/add.php
  www/srnj01/cv08/cart.php
  www/srnj01/cv08/components/nav.php
  www/srnj01/cv08/components/products.php
  www/srnj01/cv08/components/sidebar.php
  www/srnj01/cv08/db/db.php
  www/srnj01/cv08/db/eshop.php
  www/srnj01/cv08/delete.php
  www/srnj01/cv08/includes/footer.php
  www/srnj01/cv08/includes/header.php
  www/srnj01/cv08/index.php
  www/srnj01/cv08/login.php
  www/srnj01/cv08/logout.php
  www/srnj01/cv08/styles/main.css
  www/srnj01/cv08/update.php
  www/srnj01/cv08/user.php
Labels: approved

#137 adad05-cv08
  www/adad05/cv08/buy.php
  www/adad05/cv08/cart.php
  www/adad05/cv08/classes/Database.php
  www/adad05/cv08/classes/DatabaseConnection.php
  www/adad05/cv08/classes/DatabaseOperations.php
  www/adad05/cv08/classes/GoodsDB.php
  www/adad05/cv08/components/body.php
  www/adad05/cv08/components/tabs.php
  www/adad05/cv08/create-item.php
  www/adad05/cv08/css/styles.css
  www/adad05/cv08/delete-item.php
  www/adad05/cv08/edit-item.php
  www/adad05/cv08/includes/footer.php
  www/adad05/cv08/includes/head.php
  www/adad05/cv08/index.php
  www/adad05/cv08/login.php
  www/adad05/cv08/logout.php
  www/adad05/cv08/remove-item.php
Labels: needs fixing

#141 lean04-cv08
  www/lean04/cv08/auth/logout.php
  www/lean04/cv08/cart.php
  www/lean04/cv08/components/LoginForm.php
  www/lean04/cv08/components/ProductDisplay.php
  www/lean04/cv08/components/ProductForm.php
  www/lean04/cv08/create-item.php
  www/lean04/cv08/css/bootstrap.css
  www/lean04/cv08/css/styles.css
  www/lean04/cv08/database/Database.php
  www/lean04/cv08/database/ProductsDB.php
  www/lean04/cv08/edit-item.php
  www/lean04/cv08/includes/footer.php
  www/lean04/cv08/includes/header.php
  www/lean04/cv08/index.php
  www/lean04/cv08/login.php
  www/lean04/cv08/products/buy.php
  www/lean04/cv08/products/delete-item.php
  www/lean04/cv08/products/remove-item.php
Labels: approved

#143 jana19-cv08
  www/jana19/cv08/buy.php
  www/jana19/cv08/cart.php
  www/jana19/cv08/components/CategoryDisplay.php
  www/jana19/cv08/components/ProductDisplay.php
  www/jana19/cv08/components/SlideDisplay.php
  www/jana19/cv08/components/pagination.php
  www/jana19/cv08/config/constant.php
  www/jana19/cv08/css/styles.css
  www/jana19/cv08/db/CategoriesDB.php
  www/jana19/cv08/db/Database.php
  www/jana19/cv08/db/DatabaseConnection.php
  www/jana19/cv08/db/DatabaseOperations.php
  www/jana19/cv08/db/ProductsDB.php
  www/jana19/cv08/db/SlidesDB.php
  www/jana19/cv08/includes/cookies.php
  www/jana19/cv08/includes/footer.php
  www/jana19/cv08/includes/header.php
  www/jana19/cv08/index.html
  www/jana19/cv08/index.php
  www/jana19/cv08/login.php
  www/jana19/cv08/logout.php
Labels: approved

#146 lacp06-cv10
  www/lacp06/cv10/admin-check.php
  www/lacp06/cv10/buy.php
  www/lacp06/cv10/cart.php
  www/lacp06/cv10/create-item.php
  www/lacp06/cv10/db/database_eshop.php
  www/lacp06/cv10/db/db_eshop.php
  www/lacp06/cv10/delete-item.php
  www/lacp06/cv10/edit-item.php
  www/lacp06/cv10/includes/Footer.php
  www/lacp06/cv10/includes/Header.php
  www/lacp06/cv10/includes/ProductDisplay.php
  www/lacp06/cv10/index.php
  www/lacp06/cv10/login.php
  www/lacp06/cv10/logout.php
  www/lacp06/cv10/manager-check.php
  www/lacp06/cv10/registration.php
  www/lacp06/cv10/remove-item.php
  www/lacp06/cv10/styles.css
  www/lacp06/cv10/user-check.php
  www/lacp06/cv10/user-privileges.php
Labels: approved

#150 brud06-cv10
  www/brud06/cv10/admin_required.php
  www/brud06/cv10/buy.php
  www/brud06/cv10/cart.php
  www/brud06/cv10/components/GoodsDisplay.php
  www/brud06/cv10/create-item.php
  www/brud06/cv10/css/myStyle.css
  www/brud06/cv10/css/style.css
  www/brud06/cv10/db/GoodsDB.php
  www/brud06/cv10/db/UserDB.php
  www/brud06/cv10/db/database.php
  www/brud06/cv10/delete-item.php
  www/brud06/cv10/edit-item.php
  www/brud06/cv10/includes/foot.php
  www/brud06/cv10/includes/head.php
  www/brud06/cv10/index.php
  www/brud06/cv10/login.php
  www/brud06/cv10/logout.php
  www/brud06/cv10/manager_required.php
  www/brud06/cv10/registration.php
  www/brud06/cv10/remove-item.php
  www/brud06/cv10/store.php
  www/brud06/cv10/user-privileges.php
  www/brud06/cv10/user_required.php
Labels: approved

#154 mald16-cv10
  www/mald16/cv10/create-item.php
  www/mald16/cv10/db/db.php
  www/mald16/cv10/delete-item.php
  www/mald16/cv10/edit-item.php
  www/mald16/cv10/edit-user-privilege.php
  www/mald16/cv10/inc/foot.php
  www/mald16/cv10/inc/head.php
  www/mald16/cv10/index.php
  www/mald16/cv10/logic/allowed-roles.php
  www/mald16/cv10/logic/display-errors.php
  www/mald16/cv10/logic/require-login.php
  www/mald16/cv10/login.php
  www/mald16/cv10/logout.php
  www/mald16/cv10/registration.php
  www/mald16/cv10/user-privileges.php
Labels: approved

#169 adad05-cv10
  www/adad05/cv10/admin-required-error.php
  www/adad05/cv10/admin-required.php
  www/adad05/cv10/administration.php
  www/adad05/cv10/buy.php
  www/adad05/cv10/cart.php
  www/adad05/cv10/classes/Database.php
  www/adad05/cv10/classes/DatabaseConnection.php
  www/adad05/cv10/classes/DatabaseOperations.php
  www/adad05/cv10/classes/GoodsDB.php
  www/adad05/cv10/classes/Privilege.php
  www/adad05/cv10/classes/UsersDB.php
  www/adad05/cv10/components/body.php
  www/adad05/cv10/components/tabs.php
  www/adad05/cv10/create-item.php
  www/adad05/cv10/css/styles.css
  www/adad05/cv10/delete-item.php
  www/adad05/cv10/edit-item.php
  www/adad05/cv10/includes/footer.php
  www/adad05/cv10/includes/head.php
  www/adad05/cv10/index.php
  www/adad05/cv10/login.php
  www/adad05/cv10/logout.php
  www/adad05/cv10/manager-required-error.php
  www/adad05/cv10/manager-required.php
  www/adad05/cv10/register.php
  www/adad05/cv10/remove-item.php
Labels: approved

#170 talp03-cv10
  www/talp03/cv10/UserDB.php
  www/talp03/cv10/admin-required.php
  www/talp03/cv10/create-item.php
  www/talp03/cv10/index.php
  www/talp03/cv10/login.php
  www/talp03/cv10/logout.php
  www/talp03/cv10/register.php
  www/talp03/cv10/remove-item.php
  www/talp03/cv10/update-item.php
  www/talp03/cv10/user-privileges.php
  www/talp03/cv10/users
  www/talp03/cv10/utils/database.php
Labels: approved

#171 lean04-cv10
  www/lean04/cv10/auth/adminRequired.php
  www/lean04/cv10/auth/logout.php
  www/lean04/cv10/auth/managerRequired.php
  www/lean04/cv10/auth/registeredUserRequired.php
  www/lean04/cv10/cart.php
  www/lean04/cv10/components/LoginForm.php
  www/lean04/cv10/components/ProductDisplay.php
  www/lean04/cv10/components/ProductForm.php
  www/lean04/cv10/components/RegistrationForm.php
  www/lean04/cv10/create-item.php
  www/lean04/cv10/css/bootstrap.css
  www/lean04/cv10/css/styles.css
  www/lean04/cv10/database/Database.php
  www/lean04/cv10/database/ProductsDB.php
  www/lean04/cv10/database/UsersDB.php
  www/lean04/cv10/edit-item.php
  www/lean04/cv10/includes/footer.php
  www/lean04/cv10/includes/header.php
  www/lean04/cv10/index.php
  www/lean04/cv10/login.php
  www/lean04/cv10/products/buy.php
  www/lean04/cv10/products/delete-item.php
  www/lean04/cv10/products/remove-item.php
  www/lean04/cv10/register.php
  www/lean04/cv10/user-privileges.php
  www/lean04/cv10/users/set_privileges.php
Labels: approved
